---
title: "Using the package"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{using_the_package}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

Let's start by calling the package and the sample data
```{r setup}
library(forcedlabor)
```

There should be some description of the data and type of columns people should have
And then some explanation for all below

```{r}
data("new_training_sample")

new_training_data$known_non_offender <- as.factor(new_training_data$known_non_offender)
levels(new_training_data$known_non_offender) <- c(levels(new_training_data$known_non_offender),1)


################## writing the recipe ##########################################

fl_rec <- recipes::recipe(known_offender ~ .,
                          # modeling known_offender using everything else
                          data = new_training_data) |>
  # actually some are more id variables
  recipes::update_role(indID,
                       new_role = "id") |>
  # actually I don't want to use other variables in the model
  recipes::update_role(flag_region, known_non_offender,
                       ais_type, foc,
                       number_poc_port_visits,
                       distance_traveled_km,
                       new_role = "dont_use")  |>
  # and some others will be useful for preventing data leakage
  recipes::update_role(source_id_number, new_role = "control")  |>
  # Remove near-zero variance numeric predictors
  recipes::step_nzv(recipes::all_predictors())  |>
  # almost zero variance removal (I don't think we have those though)
  # Remove numeric predictors that have correlation greater the 75%
  recipes::step_corr(recipes::all_numeric(), threshold = 0.75)



######### specifying the model #################################################

# RF with hyperparameters based on sensitivity_hyper.r results
rf_spec <-
  # type of model # if no tuning # rand_forest()
  parsnip::rand_forest(trees = 500,
                       # We will tune these two hyperparameters
                       mtry = 1,
                       min_n = 15) |>
  # mode
  parsnip::set_mode("classification") |>
  # engine/package
  parsnip::set_engine("ranger", regularization.factor = 0.5)



########### training and testing scheme ########################################

## defining some parameter values based on sensitivity results
num_folds <- 5
num_bags <- 5 #10
down_sample_ratio <- 1 # downsampling ratio
# Set common seed to use anywhere that uses random numbers
num_common_seeds <- 3 #3
common_seed_tibble <- tibble::tibble(common_seed =
                                       seq(1:num_common_seeds) * 101)


# Run all common_seeds
bag_runs <- common_seed_tibble |>
  # For each common_seed, run all bags
  tidyr::crossing(tibble::tibble(bag = seq(num_bags))) |>
  # Will use different random seeds when implementing recipes for each bag
  dplyr::mutate(recipe_seed = dplyr::row_number() * common_seed) |>
  # counter
  dplyr::mutate(counter = dplyr::row_number())

## parallelization strategy
parallel_plan <- "multisession" # multisession if running from RStudio, or
# multicore if from Linux, Mac and plain R, or
# psock if multisession is not working well and you need to try something else
if (parallel_plan == "multisession"){
  utils::globalVariables("multisession")
}
free_cores <- 4 # add more if you need to do many things at the same time
oopts <- options(future.globals.maxSize = 10200*1024^2)  ## 15 GB
# options(future.globals.maxSize = 50 * 1024 ^ 3)

## CROSS VALIDATION ##
# Ensure there is no splitting across source_id across analysis and assessment
# data sets.  Need to make separate splits for each seed.
cv_splits_all <- common_seed_tibble |>
  dplyr::mutate(cv_splits = purrr::map(common_seed, function(x) {
    set.seed(x)
    rsample::group_vfold_cv(new_training_data,
                            group = source_id_number,
                            v = num_folds)
  }))


### training and prediction (scores)

tictoc::tic()
train_pred_proba <- forcedlabor::ml_train_predict(fl_rec = fl_rec,
                                             rf_spec = rf_spec,
                                             cv_splits_all = cv_splits_all,
                                             bag_runs = bag_runs,
                                             down_sample_ratio = down_sample_ratio,
                                             parallel_plan = parallel_plan,
                                             free_cores = free_cores,
                                             prediction_df = NULL)
tictoc::toc()

# 561.196 sec elapsed
# 1015.74 sec elapsed
# 1310.657 sec elapsed

# Got warning about source_id_number


####### Classification with dedpul ########################################
# alpha value will be printed

# I need to reinstall test branch of forcedlabor
tictoc::tic()
classif_res <- forcedlabor::ml_classification(data = train_pred_proba,
                                              steps = 1000, plotting = FALSE,
                                              filepath = NULL,
                                              threshold = seq(0, .99, by = 0.01),
                                              eps = 0.01,
                                              parallel_plan = parallel_plan,
                                              free_cores = free_cores)
tictoc::toc()


########### Recall and specificity #################################################

tictoc::tic()
perf_metrics <- forcedlabor::ml_perf_metrics(data = classif_res$pred_conf)
tictoc::toc()

```
