
globalVariables(c(".estimate"))
globalVariables(c(".pred_1"))
globalVariables(c("bag_downsample"))
globalVariables(c("common_seed"))
globalVariables(c("cv_df"))
globalVariables(c("holdout"))
globalVariables(c("id"))
globalVariables(c("indID"))
globalVariables(c("known_non_offender"))
globalVariables(c("known_offender"))
globalVariables(c("pred_class"))
globalVariables(c("rf_setup"))
globalVariables(c("source_id_number"))
